-- INTERVAL COSMOS ver.2.0.4
-- 初回オンライン接続用。現在のSupabase側にテストデータがない前提で再構築します。

create extension if not exists pgcrypto;

-- まだ運用開始前なので、v2.0.3以前の互換性のない空テーブルを安全に作り直します。
drop table if exists public.rankings cascade;
drop table if exists public.profiles cascade;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  student_number text not null unique check (char_length(student_number) between 3 and 20),
  player_name text not null check (char_length(player_name) between 2 and 16),
  avatar text not null default '🌟' check (char_length(avatar) between 1 and 16),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.rankings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  player_name text not null,
  avatar text not null default '🌟',
  mode text not null check (mode in ('TEXT','KEYS','HD_TEXT','HD_KEYS','EAR_LINK')),
  period text not null check (period = 'ALL' or period ~ '^[0-9]{4}-[0-9]{2}$'),
  score integer not null check (score between 0 and 500000),
  total_answers integer not null default 0 check (total_answers >= 0),
  correct_answers integer not null default 0 check (correct_answers >= 0 and correct_answers <= total_answers),
  max_combo integer not null default 0 check (max_combo >= 0),
  avg_response double precision not null default 0 check (avg_response >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, mode, period)
);

create index rankings_lookup_idx
  on public.rankings (mode, period, score desc, updated_at asc);
create index rankings_user_idx
  on public.rankings (user_id);

alter table public.profiles enable row level security;
alter table public.rankings enable row level security;

-- 学籍番号を含むprofileは本人だけ閲覧可能。
create policy "Players can read own profile"
  on public.profiles for select
  to authenticated
  using ((select auth.uid()) = id);

create policy "Players can insert own profile"
  on public.profiles for insert
  to authenticated
  with check ((select auth.uid()) = id);

create policy "Players can update own profile"
  on public.profiles for update
  to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

-- ランキング情報には学籍番号を含めない。認証済みプレイヤーは全員閲覧可。
create policy "Rankings are visible to signed-in players"
  on public.rankings for select
  to authenticated
  using (true);

-- 名前やアイコンを変更した時、ランキング表示にも反映。
create or replace function public.sync_interval_cosmos_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.rankings
     set player_name = new.player_name,
         avatar = new.avatar,
         updated_at = now()
   where user_id = new.id;
  return new;
end;
$$;

create trigger sync_interval_cosmos_profile_trigger
after update of player_name, avatar on public.profiles
for each row execute function public.sync_interval_cosmos_profile();

-- 月間ベストと殿堂入りベストを同時更新し、順位を返す。
create or replace function public.submit_interval_cosmos_score(
  p_mode text,
  p_score integer,
  p_total_answers integer,
  p_correct_answers integer,
  p_max_combo integer,
  p_avg_response double precision
)
returns table (
  monthly_rank bigint,
  hall_rank bigint,
  monthly_improved boolean,
  hall_improved boolean
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_month text := to_char(timezone('Asia/Tokyo', now()), 'YYYY-MM');
  v_name text;
  v_avatar text;
  v_rows integer;
  v_month_score integer;
  v_hall_score integer;
begin
  if v_uid is null then
    raise exception 'Authentication required';
  end if;
  if p_mode not in ('TEXT','KEYS','HD_TEXT','HD_KEYS','EAR_LINK') then
    raise exception 'Invalid mode';
  end if;
  if p_score < 0 or p_score > 500000 then
    raise exception 'Invalid score';
  end if;
  if p_total_answers < 0 or p_correct_answers < 0 or p_correct_answers > p_total_answers then
    raise exception 'Invalid answer counts';
  end if;

  select player_name, avatar
    into v_name, v_avatar
    from public.profiles
   where id = v_uid;
  if v_name is null then
    raise exception 'Player profile is required';
  end if;

  insert into public.rankings (
    user_id, player_name, avatar, mode, period, score,
    total_answers, correct_answers, max_combo, avg_response
  ) values (
    v_uid, v_name, v_avatar, p_mode, v_month, p_score,
    p_total_answers, p_correct_answers, p_max_combo, p_avg_response
  )
  on conflict (user_id, mode, period) do update
     set player_name = excluded.player_name,
         avatar = excluded.avatar,
         score = excluded.score,
         total_answers = excluded.total_answers,
         correct_answers = excluded.correct_answers,
         max_combo = excluded.max_combo,
         avg_response = excluded.avg_response,
         updated_at = now()
   where excluded.score > public.rankings.score;
  get diagnostics v_rows = row_count;
  monthly_improved := v_rows > 0;

  insert into public.rankings (
    user_id, player_name, avatar, mode, period, score,
    total_answers, correct_answers, max_combo, avg_response
  ) values (
    v_uid, v_name, v_avatar, p_mode, 'ALL', p_score,
    p_total_answers, p_correct_answers, p_max_combo, p_avg_response
  )
  on conflict (user_id, mode, period) do update
     set player_name = excluded.player_name,
         avatar = excluded.avatar,
         score = excluded.score,
         total_answers = excluded.total_answers,
         correct_answers = excluded.correct_answers,
         max_combo = excluded.max_combo,
         avg_response = excluded.avg_response,
         updated_at = now()
   where excluded.score > public.rankings.score;
  get diagnostics v_rows = row_count;
  hall_improved := v_rows > 0;

  select score into v_month_score
    from public.rankings
   where user_id = v_uid and mode = p_mode and period = v_month;
  select score into v_hall_score
    from public.rankings
   where user_id = v_uid and mode = p_mode and period = 'ALL';

  select 1 + count(*) into monthly_rank
    from public.rankings
   where mode = p_mode and period = v_month and score > v_month_score;
  select 1 + count(*) into hall_rank
    from public.rankings
   where mode = p_mode and period = 'ALL' and score > v_hall_score;

  return next;
end;
$$;

revoke all on public.profiles from anon;
revoke all on public.rankings from anon;
grant select, insert, update on public.profiles to authenticated;
grant select on public.rankings to authenticated;
grant execute on function public.submit_interval_cosmos_score(text,integer,integer,integer,integer,double precision) to authenticated;
