-- Early rewards depend on practice, not a waiting period. Earned rewards remain owned.
begin;
update public.achievement_catalog set requirement='{"type": "sessions", "count": 1}'::jsonb, description='はじめてプレイ記録を保存する。',display_name='FIRST SIGNAL' where id='first_signal';
update public.achievement_catalog set requirement='{"type": "sessions", "count": 5}'::jsonb, description='累計5回プレイする。',display_name='ORBIT STARTER' where id='sessions_5';
update public.achievement_catalog set requirement='{"type": "sessions", "count": 30}'::jsonb, description='累計30回プレイする。',display_name='ORBIT REGULAR' where id='sessions_20';
update public.achievement_catalog set requirement='{"type": "sessions", "count": 75}'::jsonb, description='累計75回プレイする。',display_name='STAR TRACKER' where id='sessions_50';
update public.achievement_catalog set requirement='{"type": "sessions", "count": 150}'::jsonb, description='累計150回プレイする。',display_name='STELLAR VETERAN' where id='sessions_100';
update public.achievement_catalog set requirement='{"type": "perfect_session", "min_answers": 15, "min_sessions": 5, "repeat_count": 2}'::jsonb, description='1プレイで15問以上・全問正解を2回。累計5プレイ。',display_name='CLEAN CONTACT' where id='perfect_5';
update public.achievement_catalog set requirement='{"type": "perfect_session", "min_answers": 20, "min_sessions": 25, "repeat_count": 3}'::jsonb, description='1プレイで20問以上・全問正解を3回。累計25プレイ。',display_name='CLEAR ORBIT' where id='perfect_10';
update public.achievement_catalog set requirement='{"type": "perfect_session", "min_answers": 30, "min_sessions": 50, "repeat_count": 5}'::jsonb, description='1プレイで30問以上・全問正解を5回。累計50プレイ。',display_name='PRECISION PILOT' where id='perfect_20';
update public.achievement_catalog set requirement='{"type": "combo", "value": 10, "min_sessions": 5, "repeat_count": 2}'::jsonb, description='10コンボ以上を2回。累計5プレイ。',display_name='COMBO 10' where id='combo_5';
update public.achievement_catalog set requirement='{"type": "combo", "value": 15, "min_sessions": 25, "repeat_count": 3}'::jsonb, description='15コンボ以上を3回。累計25プレイ。',display_name='COMBO DRIVER' where id='combo_10';
update public.achievement_catalog set requirement='{"type": "combo", "value": 25, "min_sessions": 50, "repeat_count": 3}'::jsonb, description='25コンボ以上を3回。累計50プレイ。',display_name='CHAIN 25' where id='combo_20';
update public.achievement_catalog set requirement='{"type": "combo", "value": 35, "min_sessions": 75, "repeat_count": 5}'::jsonb, description='35コンボ以上を5回。累計75プレイ。',display_name='CHAIN REACTOR' where id='combo_30';
update public.achievement_catalog set requirement='{"mode": "TEXT", "type": "mode_sessions", "count": 10}'::jsonb, description='TEXTを10回プレイする。',display_name='TEXT SPECIALIST' where id='text_10';
update public.achievement_catalog set requirement='{"mode": "KEYS", "type": "mode_sessions", "count": 10}'::jsonb, description='KEYSを10回プレイする。',display_name='KEYS SPECIALIST' where id='keys_10';
update public.achievement_catalog set requirement='{"type": "any_mode", "count": 5, "modes": ["HD_TEXT", "HD_KEYS"]}'::jsonb, description='HD TEXT / HD KEYSを合計5回プレイする。',display_name='HYPER IGNITION' where id='hyper_first';
update public.achievement_catalog set requirement='{"mode": "EAR_LINK", "type": "mode_sessions", "count": 5}'::jsonb, description='EAR LINKを5回プレイする。',display_name='EAR CONTACT' where id='ear_first';
update public.achievement_catalog set requirement='{"type": "all_modes", "modes": ["TEXT", "KEYS", "HD_TEXT", "HD_KEYS", "EAR_LINK"], "min_sessions": 15}'::jsonb, description='主要5モードをすべてプレイする。累計15回プレイ。',display_name='COSMOS EXPLORER' where id='all_modes';
update public.achievement_catalog set requirement='{"type": "interval_mastery", "min_seen": 15, "min_accuracy": 0}'::jsonb, description='13音程すべてに15回答以上。',display_name='13 SIGNALS' where id='interval_all_seen';
update public.achievement_catalog set requirement='{"type": "interval_mastery", "min_seen": 30, "min_accuracy": 80}'::jsonb, description='13音程すべてに30回答以上、正答率80%以上。',display_name='INTERVAL NAVIGATOR' where id='interval_80';
update public.achievement_catalog set requirement='{"type": "interval_mastery", "min_seen": 50, "min_accuracy": 90}'::jsonb, description='13音程すべてに50回答以上、正答率90%以上。',display_name='INTERVAL MASTER' where id='interval_90';
update public.achievement_catalog set requirement='{"days": 3, "type": "streak_days"}'::jsonb, description='3日連続でプレイする。',display_name='THREE DAY ORBIT' where id='streak_3';
update public.achievement_catalog set requirement='{"days": 7, "type": "streak_days"}'::jsonb, description='7日連続でプレイする。',display_name='SEVEN DAY ORBIT' where id='streak_7';
update public.achievement_catalog set requirement='{"days": 10, "type": "streak_days"}'::jsonb, description='10日連続でプレイする。',display_name='TEN DAY ORBIT' where id='streak_14';
update public.achievement_catalog set requirement='{"rank": 999999, "type": "public_rank", "min_sessions": 10}'::jsonb, description='ランキングへ記録を公開する。累計10回プレイ。',display_name='OPEN CHANNEL' where id='public_record';
update public.achievement_catalog set requirement='{"rank": 10, "type": "public_rank", "min_sessions": 50}'::jsonb, description='殿堂ランキング10位以内に入る。累計50回プレイ。',display_name='TOP TEN' where id='rank_top10';
update public.achievement_catalog set requirement='{"rank": 3, "type": "public_rank", "min_sessions": 100}'::jsonb, description='殿堂ランキング3位以内に入る。累計100回プレイ。',display_name='PODIUM' where id='rank_podium';
update public.achievement_catalog set requirement='{"rank": 1, "type": "public_rank", "min_sessions": 150}'::jsonb, description='殿堂ランキング1位以内に入る。累計150回プレイ。',display_name='NUMBER ONE' where id='rank_first';
update public.achievement_catalog set requirement='{"mode": "EAR_LINK", "type": "perfect_session", "min_answers": 15, "min_sessions": 50, "repeat_count": 3}'::jsonb, description='???',display_name='INNER EAR' where id='hidden_ear_perfect';
update public.achievement_catalog set requirement='{"type": "all_modes_perfect", "modes": ["TEXT", "KEYS", "HD_TEXT", "HD_KEYS", "EAR_LINK"], "min_answers": 20, "min_sessions": 75, "mode_min_answers": {"EAR_LINK": 10}}'::jsonb, description='???',display_name='FIVE PERFECT ORBITS' where id='hidden_all_mode_perfect';
update public.achievement_catalog set requirement='{"type": "combo", "value": 40, "min_sessions": 100, "repeat_count": 3}'::jsonb, description='???',display_name='GRAVITY CHAIN' where id='hidden_combo_50';
update public.achievement_catalog set requirement='{"ids": ["interval_90", "streak_14", "rank_first", "hidden_ear_perfect"], "type": "achievement_combo"}'::jsonb, description='???',display_name='SINGULARITY' where id='hidden_singularity';
update public.achievement_catalog set requirement='{"type": "sessions", "count": 250}'::jsonb, description='累計250回プレイする。',display_name='DEEP SPACE VOYAGER' where id='sessions_250';
update public.achievement_catalog set requirement='{"type": "sessions", "count": 500}'::jsonb, description='累計500回プレイする。',display_name='DEEP SPACE LEGEND' where id='sessions_1000';
update public.achievement_catalog set requirement='{"type": "perfect_session", "min_answers": 40, "min_sessions": 100, "repeat_count": 3}'::jsonb, description='1プレイで40問以上・全問正解を3回。累計100プレイ。',display_name='PRECISION ACE' where id='perfect_40';
update public.achievement_catalog set requirement='{"type": "combo", "value": 45, "min_sessions": 150, "repeat_count": 3}'::jsonb, description='45コンボ以上を3回。累計150プレイ。',display_name='APEX CHAIN' where id='combo_100';
update public.achievement_catalog set requirement='{"days": 7, "type": "active_days"}'::jsonb, description='通算7日プレイする。連続でなくてもよい。',display_name='SEVEN DAY JOURNEY' where id='streak_30';
update public.achievement_catalog set requirement='{"days": 15, "type": "active_days"}'::jsonb, description='通算15日プレイする。連続でなくてもよい。',display_name='FIFTEEN DAY CONSTELLATION' where id='streak_60';
update public.achievement_catalog set requirement='{"type": "all_modes_perfect", "modes": ["TEXT", "KEYS", "HD_TEXT", "HD_KEYS", "EAR_LINK"], "min_answers": 30, "min_sessions": 100, "mode_min_answers": {"EAR_LINK": 15}}'::jsonb, description='主要5モードそれぞれで30問以上・全問正解（EAR LINKは15問以上）。累計100プレイ。',display_name='FIVE STAR PRECISION' where id='all_modes_perfect_30';
update public.achievement_catalog set requirement='{"mode": "EAR_LINK", "type": "perfect_session", "min_answers": 20, "min_sessions": 75, "repeat_count": 3}'::jsonb, description='EAR LINKで20問以上・全問正解を3回。累計75プレイ。',display_name='DEEP LISTENER' where id='ear_perfect_40';
-- Immutable award amounts in historical ledgers are intentionally untouched.
update public.mode_clear_reward_catalog set reward_points=case mode when 'TEXT' then 40 when 'KEYS' then 40 when 'HD_TEXT' then 50 when 'HD_KEYS' then 50 when 'EAR_LINK' then 60 end;
update public.daily_mission_catalog set reward_points=case when reward_points<=30 then 60 else 80 end;
commit;
